services:
  database:
    image: mysql:latest
    build: .
    container_name: ecommerce_db_mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'ecommerce_api'
       MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    driver: local