services:
  database:
    image: mysql:latest
    build: .
    container_name: ecommerce-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_api
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    driver: local
